# Este archivo es utilizado para configurar los ajustes de behave para el proyecto Django. Contiene configuraciones específicas para la ejecución de pruebas de comportamiento (BDD) utilizando la biblioteca behave

[behave]
paths = features
no_capture = true